# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.deno
                       ~/.cache/deno
                  key: ${{ runner.os }}-deno-${{ hashFiles('**/build.ts') }}
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.22.0
                  cache: true

            - name:
                  Setup Deno
                  # uses: denoland/setup-deno@v1
              uses: denoland/setup-deno@v1.1.0
              with:
                  deno-version: v1.32.1

            - name: Build bundle
              run: sh ./build.sh

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/heads/main')
              with:
                  tag_name: Continuous-integration-${{ github.sha }}
                  #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
                  files: |
                      dist/*.zip

